# TensorFlow Basics

**tensorflow does not execute unless provided in sessions, it will only declare the object**

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.10.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
result

b'HelloWorld'

** Computations **

In [16]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [17]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [20]:
with tf.Session() as sess:
    result = sess.run(tensor_1+tensor_2)

In [21]:
result

3

## Operations

In [24]:
const = tf.constant(10)

In [27]:
fill_mat = tf.fill((4,4),10)
fill_mat

<tf.Tensor 'Fill_2:0' shape=(4, 4) dtype=int32>

In [29]:
myzeros = tf.zeros((4,4))
myzeros

<tf.Tensor 'zeros_1:0' shape=(4, 4) dtype=float32>

In [30]:
myones = tf.ones((4,4))

In [31]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [32]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [34]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [48]:
# Only run this cell once!
sess = tf.InteractiveSession() # only for jupyter notebook

C:\Users\ashis\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [49]:
for op in my_ops:
    print(op.eval()) #we can also write print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.11202732  0.21757296 -0.36113864 -0.08782282]
 [-0.2527585  -0.21817821  0.83258665  0.6826738 ]
 [ 0.12057848 -1.1821752  -0.20628886  0.4307994 ]
 [-0.2634831   0.8000722  -0.6996642   1.014139  ]]


[[0.20841861 0.24727428 0.43466818 0.3466661 ]
 [0.7409997  0.07435358 0.00495017 0.06976008]
 [0.0272814  0.92106295 0.41554904 0.41526747]
 [0.47295594 0.6956948  0.67622554 0.8966757 ]]




## Matrix Multiplication

In [50]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [51]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [56]:
b = tf.constant([[10],[100]])# here the row is 2 and the column is 1 so dim: 2x1 this is very important

In [57]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [58]:
result = tf.matmul(a,b)

In [59]:
result.eval()

array([[210],
       [430]])